/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as InstallmentsRouteImport } from './routes/installments'
import { Route as ImportRouteImport } from './routes/import'
import { Route as FiltersRouteImport } from './routes/filters'
import { Route as DuplicatesRouteImport } from './routes/duplicates'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionNewRouteImport } from './routes/transaction.new'
import { Route as TransactionIdRouteImport } from './routes/transaction.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallmentsRoute = InstallmentsRouteImport.update({
  id: '/installments',
  path: '/installments',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const FiltersRoute = FiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => rootRouteImport,
} as any)
const DuplicatesRoute = DuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionNewRoute = TransactionNewRouteImport.update({
  id: '/transaction/new',
  path: '/transaction/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionIdRoute = TransactionIdRouteImport.update({
  id: '/transaction/$id',
  path: '/transaction/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/duplicates': typeof DuplicatesRoute
  '/filters': typeof FiltersRoute
  '/import': typeof ImportRoute
  '/installments': typeof InstallmentsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/transaction/$id': typeof TransactionIdRoute
  '/transaction/new': typeof TransactionNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/duplicates': typeof DuplicatesRoute
  '/filters': typeof FiltersRoute
  '/import': typeof ImportRoute
  '/installments': typeof InstallmentsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/transaction/$id': typeof TransactionIdRoute
  '/transaction/new': typeof TransactionNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/duplicates': typeof DuplicatesRoute
  '/filters': typeof FiltersRoute
  '/import': typeof ImportRoute
  '/installments': typeof InstallmentsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/transaction/$id': typeof TransactionIdRoute
  '/transaction/new': typeof TransactionNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/duplicates'
    | '/filters'
    | '/import'
    | '/installments'
    | '/review'
    | '/settings'
    | '/transaction/$id'
    | '/transaction/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/duplicates'
    | '/filters'
    | '/import'
    | '/installments'
    | '/review'
    | '/settings'
    | '/transaction/$id'
    | '/transaction/new'
  id:
    | '__root__'
    | '/'
    | '/duplicates'
    | '/filters'
    | '/import'
    | '/installments'
    | '/review'
    | '/settings'
    | '/transaction/$id'
    | '/transaction/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DuplicatesRoute: typeof DuplicatesRoute
  FiltersRoute: typeof FiltersRoute
  ImportRoute: typeof ImportRoute
  InstallmentsRoute: typeof InstallmentsRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  TransactionIdRoute: typeof TransactionIdRoute
  TransactionNewRoute: typeof TransactionNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installments': {
      id: '/installments'
      path: '/installments'
      fullPath: '/installments'
      preLoaderRoute: typeof InstallmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filters': {
      id: '/filters'
      path: '/filters'
      fullPath: '/filters'
      preLoaderRoute: typeof FiltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duplicates': {
      id: '/duplicates'
      path: '/duplicates'
      fullPath: '/duplicates'
      preLoaderRoute: typeof DuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction/new': {
      id: '/transaction/new'
      path: '/transaction/new'
      fullPath: '/transaction/new'
      preLoaderRoute: typeof TransactionNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction/$id': {
      id: '/transaction/$id'
      path: '/transaction/$id'
      fullPath: '/transaction/$id'
      preLoaderRoute: typeof TransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DuplicatesRoute: DuplicatesRoute,
  FiltersRoute: FiltersRoute,
  ImportRoute: ImportRoute,
  InstallmentsRoute: InstallmentsRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  TransactionIdRoute: TransactionIdRoute,
  TransactionNewRoute: TransactionNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
